### ISSUE TITLE
Portal to new level

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unreal-SharedSpaces#15]
Before updating to OVR I had succesfully created a portal to a new level that I had created but after update now when moving to my new level the character does not appear and camera is rooted to 0,0,0. 

To confirm, to create a portal to a new level the level only needs to have same name as destination API name? Or is there something extra to add. an entry to a datalist etc?

**Comment by els-oculus** [comment]
In the case of SharedSpaces, the association between the level and the destination is stored in the destination's deeplink message.  As an example, look at the Green Room: 

![greenroom](https://user-images.githubusercontent.com/61444568/170142569-de75af48-d7e2-44df-90a5-f6f91ba98037.png)

The portal instances all have parameters that need to be filled in.   Again, for the Green Room:

![greendoor_data](https://user-images.githubusercontent.com/61444568/170142356-5fda1527-072d-46bb-a7e2-bea129a7b07b.png)

Open the portal blueprint to see how the destination is found and how we extract the data we need from the deeplink.

![launchmap](https://user-images.githubusercontent.com/61444568/170143259-ccd361b2-43bb-42d4-8b04-c2f58c5b051f.png)

Another important aspect of those portals is that we also put a "PlayerStart" actor in front of them so that we can have a spawn location corresponding to the door they come from.

![spawn](https://user-images.githubusercontent.com/61444568/170143075-a027a480-fe20-4193-8622-0a6a1da7818f.png)

There's a lot to explore in those blueprints and C++ code.  :)

Good luck!

**Comment by owlandfox** [comment]
That worked thanks!

**Comment by owlandfox** [comment]
Is there a finite number of portals that can be placed in lobby? Ive just created a new fifth portal with all the correct attributes and im getting the same behaviour of the player spawning at 0,0,0 and no control. Everything is correctly in place so im wondering if the limit is 4 portals?

**Comment by owlandfox** [comment]
Actually its fixed. Just needed to turn it off and on again haha!
