### ISSUE TITLE
PhotonNetDriver : how to use it without Oculus auth ?

### ISSUE THREAD

**Issue by loyhaim** [oculus-samples/Unreal-SharedSpaces#21]
Hi,

I'm trying to use the PhotonNetDriver without Ovr, as I want to test multiplayer locally without the burden of deploying on the Quest during dev time. But I see it's using the IP from the host which is retrieved through OVR Platform plugin.

![image](https://user-images.githubusercontent.com/8579649/173203973-993d640a-0835-424e-8ef5-e504b8e790d9.png)

1. Does it mean we can't use PhotonNetDriver without OvrPlatform at all ? Or how can we do that ?
2. Not sure to understand why we want the IP from the host, wouldn't everything go through Photon and so the IP would be masked ? 

By the way, thank you for all the work already achieved !

**Comment by els-oculus** [comment]
Let's first clarify that in the case of our Photon communication, **the host address is not an IP address.**

- The "host address" that we use for Photon has the form "1234567890.oculus", where 1234567890 is some large identifier that is the app-specific user id of the player hosting the session.  For Oculus apps, user identifiers are unique per application.
- Communication is indeed reflected through the Photon backend and players IP addresses are not revealed.

Now regarding the OVR Platform library: it works on Quest (Android) and Windows, with the exception of in game system panels.

- Most of the OVR Platform calls will work properly on PC during development as long as you also have a Rift app id in your config file: you can log in, you can query leaderboards, etc.
- Unfortunately the Oculus system panels (roster panel, invite panel, etc.) will only appear on device, so that will not work without pushing to headset.  Note that all the Play-in-Editor (PIE) modes are actually running on PC, require a Rift id, and suffer from those limitations.

I hope this helps a bit!  :)

**Comment by loyhaim** [comment]
Ok, merci beaucoup Eric, that's clear and reassuring.

Seems like I missed something on my rift configuration, I'm going to check it again.
