### ISSUE TITLE
Desktop build

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unreal-SharedSpaces#23]
Is there any way to get Shared Spaces working in a desktop (non VR) build? I realise the main requirement is that user has Oculus app installed and logged in but it would be great if there was a way round this so that we could expand Shared Spaces experiences to desktop builds and maybe even pixel streaming / cloud gaming. Maybe somehow allowing user (without Oculus app installed) to login to Oculus via a modal in game to activate the functionality?

**Comment by els-oculus** [comment]
The OVR Platform C library *does* have calls that allow you to authenticate in other ways, but we have not exposed them through our UE4 plugin.    I added a task so that we do just that as it is very convenient for a variety of situations.

The functions that you are interested in are in [OVR_Platform.h](https://github.com/Oculus-VR/UnrealEngine/blob/071a3f414c927ed9419ebfab0b9172990d5ad3a4/Engine/Source/ThirdParty/Oculus/LibOVRPlatform/LibOVRPlatform/include/OVR_Platform.h#L214).  **ovr_Platform_InitializeStandaloneOculus()** allows you to supply username/password, which can be OK if you trust the machine that this is used on.   Could be fine with test users credentials, as an example.

**Comment by els-oculus** [comment]
Well, I looked back into this today and noticed that... this is already implemented in OVRPlatformSubsystem.cpp!  :)

Just add the credentials of the user that you want to login as in DefaultEngine.ini:

[OnlineSubsystemOculus]
MobileAppId=<your quest app id>
RiftAppId=<your windows app id>
OculusEmail=<the email of the user to log in as>
OculusPassword=<that user's password>

You can find the credentials of your tests users on dashboard.oculus.com.

**Comment by owlandfox** [comment]
Amazing! this opens things up a lot :) Hopefully we can just plug some UMG to that code so that any user can login. Hopefully the client/server multiplayer system works accordingly using this method too. Ill let you know!

**Comment by els-oculus** [comment]
Note that this is only for Windows, and should mostly be used for testing.

You may find it more useful to read the credentials on the command line, which would also allow you to run multiple servers on a single PC.   Look at OVRPlatformSubsystem.cpp at line 209, you will see that we have code for reading OculusEmail and OculusPassword as command line arguments.
