### ISSUE TITLE
Global UI Settings modal

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unreal-SharedSpaces#35]
We are trying to create a global UI modal that works similar to how the current Roster, Invite UI panels work = character movement is stopped and UI pops up in between avatar and camera. We are having some trouble replicating this functionality in getting our controller to hit our UI and other issues. We really want to stay consistent with the current roster and invite panels so is there some way of replicating these BPs and switching out the UI panels therein?

We basically want a global UI popup (on button press) where user can select/change their avatar mesh and some other in game features.

**Comment by yvasquezmonoku** [comment]
Hello, to make an interface where the user can interact. you can create an actor and there you put the widget, since in vr the interfaces must be in 3D. Now if you want to replicate it so that the other players also see the interface that a player invoked, you must replicate that actor.
I leave you a video of how to create an interface in vr
https://www.youtube.com/watch?v=8q_2z-SwcZY&ab_channel=Just2Devs

**Comment by els-oculus** [comment]
The Roster and Invite panels are generated by the system.
The only thing SharedSpaces does is to launch them.   There's no other work in SharedSpaces.

So as yvasquezmonoku suggested, this will require from you some Unreal Engine UI work.
Here's a solid example: https://github.com/Oculus-VR/UnrealEngine/tree/4.27/Samples/Oculus/HandsTrainSample
