### ISSUE TITLE
Can I get the title of a leaderboard from OVR Platform?

### ISSUE THREAD

**Issue by yvasquezmonoku** [oculus-samples/Unreal-SharedSpaces#41]
We have implemented some leaderboards, and we would like that when displaying them, they will take the name of the title of each leaderboard given in the development page, in order to change them later from the page.

**Comment by els-oculus** [comment]
For testing, I created two new leaderboards, **green_room_leaderboard** and **red_room_leaderboard**.   The only reason I linked the leaderboards to a destination is because it is an option.  I can retrieve _ALL_ leaderboards with a blueprint like this one by not specifying a name (I did not know I could do that, the API doc says it's for a specific leaderboard).

![leaderboards](https://user-images.githubusercontent.com/61444568/189005327-f79c9ba0-a0ce-4fee-960c-6bfc3b50fd91.png)

(notice that I did not specify a leaderboard name to retrieve them all)

![log](https://user-images.githubusercontent.com/61444568/189005639-7d84d646-b30c-437a-b672-b59cd1cb437f.jpg)

Unfortunately, the "Title" is not part of the exposed leaderboard structure.   Only ID, api_name and destination.

I'll ask internally if we can expose more, and the title in particular.

**Comment by yvasquezmonoku** [comment]
Okay, I'll keep an eye out. Thanks a lot

**Comment by els-oculus** [comment]
I filed a request to add more fields internally, with the proper team.
It takes a while for the SDK to be updated, so I strongly suggest that you try to work around this limitation in some other way.

I'll close this as this is not specific to SharedSpaces.
