### ISSUE TITLE
Disable shared spaces at a specific level

### ISSUE THREAD

**Issue by yvasquezmonoku** [oculus-samples/Unreal-SharedSpaces#45]
Hi! we have a level editor which we would like to disable shared spaces, since when the user takes off his glasses or goes out to the ps, the level restarts and the work is lost. We would like this level to load locally since no one will be invited to this level, if not only the main player will be there, is this possible?

**Comment by els-oculus** [comment]
If I understand correctly, it could be something like making some rooms "private", for the user only, and they could "edit" that room.   In that case, you would like to bypass all the disconnect/reconnect logic that makes those changes lost.

Yes, that's entirely possible.   Off the top of my head, I would add some flag to mark a destination as "private".
When it is private, I would bypass the Photon networking altogether, since I do not need to be connected to other players.

I am sure that there are a number of details that would need some polishing to support that new type of room, but yeah, it is definitely possible.

**Comment by yvasquezmonoku** [comment]
Thank you very much for answering. When you say add a flag that indicates when a room is private or not, in what part do you mean that this flag is added?

**Comment by els-oculus** [comment]
I would store that as a new attribute in the destination deeplink on the dashboard.  **is_lobby** is a good example to follow.

![lobbydashboard](https://user-images.githubusercontent.com/61444568/199357550-841e26a9-a32a-4eb5-b080-c76559652463.png)

We have code to extract that field from the deeplink in Source\SharedSpaces\Public\SharedSpacesFunctionLibrary.h.   It creates this node that you can use directly in the SharedSpacesGameInstance blueprint. 

![islobby](https://user-images.githubusercontent.com/61444568/199356858-3a5af2f2-f1d5-4ceb-9b55-6d29ca46cbfb.png)

I would probably call this new attribute **is_private** and would then figure out how to skip the networking altogether.  You have to handle going from public to private destinations, from private back to public, private to private.

Let us know how it goes!

**Comment by yvasquezmonoku** [comment]
Thank you very much, everything works perfectly as I wanted. Create a function based on "get is lobby" and leave this after it loads the room. When it validates that the room is private, I disconnect from photon and immediately charge the level. I did this like this, because if I do it before the room loads, when I enter the oculus menu I can see that it tells me that I am in the lobby and it lets me invite, leaving it after the level loads, it shows me the last room in this case I want her without invite options.
![image](https://user-images.githubusercontent.com/38009822/199502670-ab5d9782-efa2-47b4-940e-c174ceebf67d.png)
