### ISSUE TITLE
Quest Profile Image and User Names Replication

### ISSUE THREAD

**Issue by deedox** [oculus-samples/Unreal-SharedSpaces#60]
Hi, I'm trying to apply Quest user names and images to the players. I'm struggling a bit with proper replication, it works when I play alone but when another player joins no images are applied and names are shown as "Text" I would be thankfull for any advice.

![Screenshot 2023-03-09 153801](https://user-images.githubusercontent.com/9035271/224058620-9144a641-a46e-4961-a0e3-1a46591ea254.jpg)

**Comment by AlexThiv** [comment]
Hi @deedox,

Seems like the nodes above only gets the logged in user info rather than the other users. You can check how we handle the player name replication and would probably want to replicate the image url.

In the SharedSpacesCharacter "CLIENT - Sending name to server." you will see the call to "Notify Server of Name" which in turn will set the character name on the entity.

Hopefully this points you in the right direction. Let me know how it turns out and if I can help further.

**Comment by deedox** [comment]
Hi, sorry for the late reply. I was very buss the last month. I hope that you still can help me.
I manage to make the names working but I'm  struggling with the user images. This how far I came but with no luck. I'm not able to download the user image for the client characters..
Basically what I want is get each users image and apply them to my custom character mesh.
![usrimg_1](https://user-images.githubusercontent.com/9035271/230528550-28f41cf2-6a8a-4dec-a981-8ea5667fdce1.jpg)
![usrimg_2](https://user-images.githubusercontent.com/9035271/230528552-38e36e3b-fc22-484d-9a92-77be773c7cb0.jpg)
