### ISSUE TITLE
App Is crashing when opening 

### ISSUE THREAD

**Issue by Jdongre** [oculus-samples/Unreal-SharedSpaces#82]
I did all the steps created photon app id and uploaded the app in dashboard but the issue i am facing is when i open the app in quest its crashing any help would be appreciated

**Comment by alefriant** [comment]
Hey @Jdongre I may could help you, in first place, which version of UE are you using? Epic or Oculus?
I recommend you to try this one (none of the others SDK and Unreal versions worked for me): UnrealEngine-oculus-5.3.2-release-1.97.0-v65.0
- https://github.com/oculus-vr/UnrealEngine/

Careful about the Antivirus, you'll need to add these exceptions, I did it in Avast, Defender from Windows could delete everything even if you add the exeptions:

**Did you created destinations and configured all the DUC requirements listed here in the SharedSpaces readme**?

**Do you have all the mentioned in this list? (I have my own recipe, but this list could be useful, seems functional)**
- https://dev.epicgames.com/community/learning/tutorials/3Vx6/unreal-engine-5-3-2-for-meta-quest-vr

Good luck! 

![image](https://github.com/user-attachments/assets/c785fc53-1377-4b8b-9c5d-d5ecd6ff14b5)


![image](https://github.com/user-attachments/assets/d7e1254d-dba8-463a-9941-f43e6ba1b935)

**Comment by jasonmeisel** [comment]
Could you provide the following information:

1. Which Quest device is it crashing on?
2. Which version of Unreal Engine are you using?
3. Is there any output from this command when it crashes? `adb logcat -s "*:F"`

**Comment by Jdongre** [comment]
Hi Jason,
      Thanks for reaching out! I was able to solve the crashing issue, but now I'm facing a problem where my lobby isn't loading—I'm getting stuck in the Teleportation map. I've created destinations, configured all the DUC requirements listed in the Shared Spaces readme, and added the necessary elements in data checkup, including the app ID and Photon ID in their respective places. Your help would be much appreciated!

Regards ,
Jayesh
________________________________

**Comment by alefriant** [comment]
@Jdongre 

Did you submitted all your maps?
Did you submitted the .obb files if any? (I've been stuck in the loading scene because this several times because I press continue in the Meta Developers hub and the obbs are hidden in the second screen, XD)
If yes ->
I suggest you to check the destination names to match correctly your map names, check if these are enabled, etc. Attached an example of the Lobby, the new destinations portal is a bit different than the readme pictures from SharedSpaces, today has more slots to fill, this could help. 

![image](https://github.com/user-attachments/assets/c724d3bb-ea3d-4aa0-bac4-cb66156f508b)

![image](https://github.com/user-attachments/assets/dd337ae9-e55e-4035-ba44-7d34dd203a32)

**Comment by Jdongre** [comment]
Hii  Alejandro
Is it necessary to store all maps in one folder ?
________________________________

**Comment by alefriant** [comment]
Hey @Jdongre , is not necessary at all. I have the things organized like that.
Just be aware of redirecting all the maps properly. 

Example:
Game/Folder1/Map1
Game/Folder1/Map2
Game/Map3
Game/Folder2/Map4
Game/OtherFolder/Folder3/Map5
etc...

Where Game is the root folder of Unreal. Good luck!

**Comment by Jdongre** [comment]
I feel the connection is not establishing between photon or oculus i dont know  i tried putting lobby as my startup map instead of transition map it opened  but the invite panel roster panel room travelling any of these feature are not available  i checked my Data use checkup all of the things required are active
________________________________

**Comment by Jdongre** [comment]
Also i am using EPIC's Unreal Engine
________________________________

**Comment by alefriant** [comment]
Hey again @Jdongre 
I tested sharedspaces like a year ago with Epic's build and it works too, so shouldn't be a problem, specially if you are getting the apk without errors. (you'll always have a few errors, but it works anyways)
I'm pretty sure that your problem is related with destinations or maps or both, I suggest you to dig on that area. 
And maybe the Meta XR SDK? Check the version compatible with Sharedspaces, in my particular case it runs with v65, but during this time I've doing several modifications to the code, they offer it running with the v59. 
Anyways, this smells as maps/destinations.

**Comment by jasonmeisel** [comment]
I'm sorry to hear you're still having trouble! What was the resolution to your crash issue?

As for your current issue, could you try running `adb logcat -s "*:F" -s "UE"` (to see the logs while the app loads and then gets stuck) and respond with the output?

**Comment by Jdongre** [comment]
[cid:cccff2df-b1f2-494f-a78b-a363043dd07d]Hii I tried the logact i am getting this could you help me understand this is it due to sdk?
________________________________

**Comment by Jdongre** [comment]
Also i wanted to know instead of third person character i want vr pawn what changes would  be required for its working
________________________________

**Comment by Jdongre** [comment]
Hii I fixed the map issue but now my  controllers are not working the third person character is  not moving and also I tried the vr pawn in that also the controlles input is not working can you help me to replace the third person character with vr Pawn
________________________________

**Comment by jasonmeisel** [comment]
Since you were able to fix the app crashing, I'm going to close this. If you have additional bugs to report, feel free to open a new issue.
