### ISSUE TITLE
Destinations Pending Review for more than 1 month?

### ISSUE THREAD

**Issue by tomfurrier** [oculus-samples/Unreal-SharedSpaces#9]
![image](https://user-images.githubusercontent.com/6026692/164280769-54d4ad6c-6577-423f-8ab3-10d50d9dc353.png)
We just want to give the sample a go, is there anything else we have to do to get these approved?

**Comment by els-oculus** [comment]
Hello Tom,

First, the message a misleading: destinations are not pending review before you try to publish your app.  We'll try to get that message fixed.  What it should really say is something like "for development only, pending review at publish time".

Second, you definitely do not need the destinations to be approved to start testing.  Are you seeing any other issues that you thought were caused by the destinations not yet being approved?

**Comment by tomfurrier** [comment]
Hi there,

thank you for your response, and we managed to test it in the current state!
